preprocess:
  dbscan_eps: 0.008
  dbscan_min_points: 10

free_space:
  voxel_size: 0.003
  fruit_max_size: 0.05
  free_space_layer: 0
  free_space_bbx_scale: 1.5

branch_completion:
  cylinder_resolution: 0.003

fruit_completion:
  deepsdf_dir: ssc_lmap/HortiMapping/deepsdf/models/sweetpepper_32
  opt_mesh_res: 16
  fruit_min_size: 0.01
  num_correspondence: 10
  NUM_ITERS: 300
  lr: 0.01
  output_mesh_res: 128
  weights:
    weight_surface: 1.0
    weight_negative: 2.0 
    weight_peduncle: 0.1
    weight_regularization: 1.0
    peduncle_tolerance: 0.0
    weight_neg_com_branch: 0.1

